/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'amount' : IDL.Text,
});
export const RecipeId = IDL.Nat;
export const Time = IDL.Int;
export const Recipe = IDL.Record({
  'id' : RecipeId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'steps' : IDL.Vec(IDL.Text),
  'ingredients' : IDL.Vec(Ingredient),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRecipe' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Ingredient), IDL.Vec(IDL.Text)],
      [RecipeId],
      [],
    ),
  'deleteRecipe' : IDL.Func([RecipeId], [], []),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecipe' : IDL.Func([RecipeId], [Recipe], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRecipes' : IDL.Func([IDL.Principal], [IDL.Vec(Recipe)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRecipe' : IDL.Func(
      [RecipeId, IDL.Text, IDL.Text, IDL.Vec(Ingredient), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Ingredient = IDL.Record({ 'name' : IDL.Text, 'amount' : IDL.Text });
  const RecipeId = IDL.Nat;
  const Time = IDL.Int;
  const Recipe = IDL.Record({
    'id' : RecipeId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'steps' : IDL.Vec(IDL.Text),
    'ingredients' : IDL.Vec(Ingredient),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRecipe' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Ingredient), IDL.Vec(IDL.Text)],
        [RecipeId],
        [],
      ),
    'deleteRecipe' : IDL.Func([RecipeId], [], []),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecipe' : IDL.Func([RecipeId], [Recipe], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRecipes' : IDL.Func([IDL.Principal], [IDL.Vec(Recipe)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRecipe' : IDL.Func(
        [RecipeId, IDL.Text, IDL.Text, IDL.Vec(Ingredient), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };