/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ingredient { 'name' : string, 'amount' : string }
export interface Recipe {
  'id' : RecipeId,
  'title' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'steps' : Array<string>,
  'ingredients' : Array<Ingredient>,
}
export type RecipeId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRecipe' : ActorMethod<
    [string, string, Array<Ingredient>, Array<string>],
    RecipeId
  >,
  'deleteRecipe' : ActorMethod<[RecipeId], undefined>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecipe' : ActorMethod<[RecipeId], Recipe>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRecipes' : ActorMethod<[Principal], Array<Recipe>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRecipe' : ActorMethod<
    [RecipeId, string, string, Array<Ingredient>, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];